#!/usr/bin/env bash
# copy files remotly
if [ -z "$1" ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
else 
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
