#!/usr/bin/env bash
# install nginx and start its

sudo apt -y update
sudo apt install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > sudo tee /var/www/html/index.html
sudo service nginx start