#!/usr/bin/env bash
# install nginx and start its

sudo apt -y update
sudo apt install -y nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start