#!/usr/bin/env bash
# Installs nginx server

sudo apt -y update
sudo apt -y install nginx 
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

SERVER=\
"server {
    listen 80 default_server;
    root /var/www/html;

    rewrite ^/redirect https://abdisa.tech;

    location /redirect {
        return 301;
    }
}"

echo -e "$SERVER" > "/etc/nginx/site-enabled/default"
nginx -s reload