#!/usr/bin/env bash
# Installs nginx server

sudo apt -y update
sudo apt -y install nginx 
ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

SERVER=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    server_name _;
    location /redirect {
        return 301 https://abdisa.tech;
    }
}"

echo -e "$SERVER" > "/etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi