#!/usr/bin/env bash
# print Best School 10 time and Hi on line 9
i=0
while [ $i -ne 10 ]
    do
        echo Best School
        if [ $i -eq 8 ]; then
                echo Hi
        fi
    (( i++ ))
    done