#!/usr/bin/env bash
# bad luck numbers
i=1
while [ $i -lt 20 ]
    do
        case $i in
            4) 
                echo bad luck from China
            ;;
            8) 
                echo bad luck from Japan
            ;;
            17) 
                echo bad luck from Italy
            ;;
            *)
                echo $i
            ;;
        esac
    (( i++ ))
    done